# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.resize(1306, 841)
        TabWidget.setDocumentMode(False)
        TabWidget.setTabsClosable(False)
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 661, 791))
        self.groupBox.setObjectName("groupBox")
        self.stopBtn = QtWidgets.QPushButton(self.groupBox)
        self.stopBtn.setGeometry(QtCore.QRect(110, 520, 41, 41))
        self.stopBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stopBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/stop-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopBtn.setIcon(icon)
        self.stopBtn.setIconSize(QtCore.QSize(24, 24))
        self.stopBtn.setObjectName("stopBtn")
        self.graphicsView = QtWidgets.QGraphicsView(self.groupBox)
        self.graphicsView.setGeometry(QtCore.QRect(10, 30, 644, 484))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setObjectName("graphicsView")
        self.pauseBtn = QtWidgets.QPushButton(self.groupBox)
        self.pauseBtn.setGeometry(QtCore.QRect(60, 520, 41, 41))
        self.pauseBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pauseBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/pause-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseBtn.setIcon(icon1)
        self.pauseBtn.setIconSize(QtCore.QSize(24, 24))
        self.pauseBtn.setObjectName("pauseBtn")
        self.playBtn = QtWidgets.QPushButton(self.groupBox)
        self.playBtn.setGeometry(QtCore.QRect(10, 520, 41, 41))
        self.playBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.playBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/play-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playBtn.setIcon(icon2)
        self.playBtn.setIconSize(QtCore.QSize(24, 24))
        self.playBtn.setObjectName("playBtn")
        self.speedUp2 = QtWidgets.QPushButton(self.groupBox)
        self.speedUp2.setGeometry(QtCore.QRect(340, 520, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.speedUp2.setFont(font)
        self.speedUp2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.speedUp2.setObjectName("speedUp2")
        self.speedUp4 = QtWidgets.QPushButton(self.groupBox)
        self.speedUp4.setGeometry(QtCore.QRect(400, 520, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.speedUp4.setFont(font)
        self.speedUp4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.speedUp4.setObjectName("speedUp4")
        self.slowDown4 = QtWidgets.QPushButton(self.groupBox)
        self.slowDown4.setGeometry(QtCore.QRect(160, 520, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.slowDown4.setFont(font)
        self.slowDown4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.slowDown4.setObjectName("slowDown4")
        self.slowDown2 = QtWidgets.QPushButton(self.groupBox)
        self.slowDown2.setGeometry(QtCore.QRect(220, 520, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.slowDown2.setFont(font)
        self.slowDown2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.slowDown2.setObjectName("slowDown2")
        self.speedUp1 = QtWidgets.QPushButton(self.groupBox)
        self.speedUp1.setGeometry(QtCore.QRect(280, 520, 51, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.speedUp1.setFont(font)
        self.speedUp1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.speedUp1.setObjectName("speedUp1")
        self.prevVideoBtn = QtWidgets.QPushButton(self.groupBox)
        self.prevVideoBtn.setGeometry(QtCore.QRect(540, 520, 51, 41))
        self.prevVideoBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prevVideoBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/backward-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prevVideoBtn.setIcon(icon3)
        self.prevVideoBtn.setIconSize(QtCore.QSize(24, 24))
        self.prevVideoBtn.setObjectName("prevVideoBtn")
        self.nextVideoBtn = QtWidgets.QPushButton(self.groupBox)
        self.nextVideoBtn.setGeometry(QtCore.QRect(600, 520, 51, 41))
        self.nextVideoBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nextVideoBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/forward-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextVideoBtn.setIcon(icon4)
        self.nextVideoBtn.setIconSize(QtCore.QSize(24, 24))
        self.nextVideoBtn.setObjectName("nextVideoBtn")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(680, 10, 611, 791))
        self.groupBox_2.setObjectName("groupBox_2")
        self.facePoolsScrollArea = QtWidgets.QScrollArea(self.groupBox_2)
        self.facePoolsScrollArea.setGeometry(QtCore.QRect(10, 30, 591, 751))
        self.facePoolsScrollArea.setWidgetResizable(True)
        self.facePoolsScrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.facePoolsScrollArea.setObjectName("facePoolsScrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 589, 749))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.facePoolsScrollArea.setWidget(self.scrollAreaWidgetContents_2)
        TabWidget.addTab(self.tab, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 861, 791))
        self.groupBox_3.setObjectName("groupBox_3")
        self.keyFramesScrollArea = QtWidgets.QScrollArea(self.groupBox_3)
        self.keyFramesScrollArea.setGeometry(QtCore.QRect(9, 29, 841, 721))
        self.keyFramesScrollArea.setWidgetResizable(True)
        self.keyFramesScrollArea.setObjectName("keyFramesScrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 839, 719))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.keyFramesScrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.clearKeyFramesBtn = QtWidgets.QPushButton(self.groupBox_3)
        self.clearKeyFramesBtn.setGeometry(QtCore.QRect(770, 760, 81, 21))
        self.clearKeyFramesBtn.setObjectName("clearKeyFramesBtn")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_4.setGeometry(QtCore.QRect(880, 10, 411, 791))
        self.groupBox_4.setObjectName("groupBox_4")
        self.facesScrollArea = QtWidgets.QScrollArea(self.groupBox_4)
        self.facesScrollArea.setGeometry(QtCore.QRect(9, 29, 391, 751))
        self.facesScrollArea.setWidgetResizable(True)
        self.facesScrollArea.setObjectName("facesScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 389, 749))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.facesScrollArea.setWidget(self.scrollAreaWidgetContents)
        TabWidget.addTab(self.tab1, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "CrimeCamera VMS"))
        self.groupBox.setTitle(_translate("TabWidget", "Camera view"))
        self.speedUp2.setText(_translate("TabWidget", "2x"))
        self.speedUp4.setText(_translate("TabWidget", "4x"))
        self.slowDown4.setText(_translate("TabWidget", "0.25x"))
        self.slowDown2.setText(_translate("TabWidget", "0.5x"))
        self.speedUp1.setText(_translate("TabWidget", "1x"))
        self.groupBox_2.setTitle(_translate("TabWidget", "Faces pool"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab), _translate("TabWidget", "Single Video"))
        self.groupBox_3.setTitle(_translate("TabWidget", "Key frames view"))
        self.clearKeyFramesBtn.setText(_translate("TabWidget", "Clear"))
        self.groupBox_4.setTitle(_translate("TabWidget", "Faces in database"))
        TabWidget.setTabText(TabWidget.indexOf(self.tab1), _translate("TabWidget", "Face Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    from gui_core.slots import SlotsHandler
    from logic.system import System

    system = System()
    slots_handler = SlotsHandler(ui, TabWidget, system)
    TabWidget.show()
    sys.exit(app.exec_())

